name: Create a new release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Embed the version string
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        sed -i "s/0.0.1/${VERSION}/g" kd.py
        chmod +x kd.py
        mv kd.py kd
    - name: Upload the binary to GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          kd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
